config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :users do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include ApplicationHelper

  def create
    type = type_subject?(params)[0]
    @subject = type_subject?(params)[1]
    notice_type = "like-#{type}"
    return unless @subject

    if already_liked?(type)
      dislike(type)
    else
      @like = @subject.likes.build(user_id: current_user.id)
      if @like.save
        flash[:success] = "#{type} liked!"
        @notification = new_notification(@subject.user, @subject.id, notice_type)
        @notification.save
      else
        flash[:danger] = "#{type} like failed!"
      end
      redirect_back(fallback_location: root_path)
    end
  end

  private

  # Returns the subject being liked (comment or post)
  def type_subject?(params)
    type = 'post' if params.key?('post_id')
    type = 'comment' if params.key?('comment_id')

    subject = Post.find(params[:post_id]) if type == 'post'
    subject = Comment.find(params[:comment_id]) if type == 'comment'

    [type, subject]
  end

  # Dislike the liked comment or post
  def dislike(type)
    @like = Like.find_by(post_id: params[:post_id]) if type == 'post'
    @like = Like.find_by(comment_id: params[:comment_id]) if type == 'comment'
    return unless @like

    @like.destroy
    redirect_back(fallback_location: root_path)
  end

  # Returns whether a post or comment has already been liked by the current_user signed in
  def already_liked?(type)
    result = false
    if type == 'post'
      result = Like.where(user_id: current_user.id, post_id:
      params[:post_id]).exists?
    end
    if type == 'comment'
      result = Like.where(user_id: current_user.id, comment_id:
      params[:comment_id]).exists?
    end

    result
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_comments.html.erb
<%= object.likes.count %>
<%= link_to comment_likes_path(object), class: "text-light", method: :post do %>
  <% if liked?(subject = object, type = 'comment') %>
      <button class="btn btn-liked"><i class="fas fa-thumbs-up"></i></button>
    <% else %>
      <button class="btn btn-neutral"><i class="fas fa-thumbs-up"></i></button>
  <% end %>
<% end %>

app/views/likes/_like_posts.html.erb
<%= object.likes.count %>
<%= link_to post_likes_path(object), class: "text-light", method: :post do %>
  <% if liked?(object, 'post') %>
      <button class="btn btn-liked"><i class="fas fa-thumbs-up"></i></button>
    <% else %>
      <button class="btn btn-neutral"><i class="fas fa-thumbs-up"></i></button>
  <% end %>
<% end %>