config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # devise_scope :users do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  put '/users/:id', to:  'users#update_img'
  get '/saw_notification', to: 'users#saw_notification', as: 'saw_notice'

  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :friend_sent, class_name: 'Friendship', foreign_key: 'sent_by_id', inverse_of: 'sent_by', dependent: :destroy
  has_many :friend_request, class_name: 'Friendship', foreign_key: 'sent_to_id',
                            inverse_of: 'sent_to', dependent: :destroy
  has_many :friends, -> { merge(Friendship.friends) }, through: :friend_sent, source: :sent_to
  has_many :pending_requests, -> { merge(Friendship.not_friends) }, through: :friend_sent, source: :sent_to
  has_many :recieved_requests, -> { merge(Friendship.not_friends) }, through: :friend_request, source: :sent_by
  has_many :notifications, dependent: :destroy
  mount_uploader :image, PictureUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  validates :fname, length: { in: 3..15 }, presence: true
  validates :lname, length: { in: 3..15 }, presence: true
  validate :picture_size

  def full_name
    "#{fname} #{lname}"
  end

  # Returns all posts from this user's friends and self
  def friends_and_own_posts
    myfriends = friends
    our_posts = []
    myfriends.each do |f|
      f.posts.each do |p|
        our_posts << p
      end
    end

    posts.each do |p|
      our_posts << p
    end

    our_posts
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.first_name # assuming the user model has a first name
      user.lname = auth.info.last_name # assuming the user model has a last name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  private

  # Validates the size of an uploaded picture.
  def picture_size
    errors.add(:image, 'should be less than 1MB') if image.size > 1.megabytes
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @friends = current_user.friends
    @pending_requests = current_user.pending_requests
    @friend_requests = current_user.recieved_requests
  end

  def show
    @user = User.find(params[:id])
  end

  def update_img
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      redirect_back(fallback_location: users_path(current_user))
      return
    end

    image = params[:user][:image] unless params[:user].nil?
    if image
      @user.image = image
      if @user.save
        flash[:success] = 'Image uploaded'
      else
        flash[:danger] = 'Image uploaded failed'
      end
    end
    redirect_back(fallback_location: root_path)
  end

  # Modifies current user's notice_seen column to true
  def saw_notification
    current_user.notice_seen = true
    current_user.save
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2 class="center"> Who do you want To <span class="font-courgette size-80">Spy</span> On? </h2>
<br>

<div class="container col-md-8">

<% unless @friends.empty? %>
  <div class="card my-5 py-3 bg-light shadow">
      <h2 class="center pb-3 text-dark border-bottom">My Friends</h2> 
      <% @friends.each do |f|%> <!-- Shows all users that have accepted current user's friend request and have become friends  -->
        <div class="d-flex align-items-center mb-2 border-bottom py-2">
          <div class="col-auto p-0 pl-5 text-capitalize">
            <%= link_to user_path(f) do %>
              <%= f.full_name %>
            <% end %>
          </div>
          <div class="col-auto p-0 px-1">|</div>
          <div class="col-auto p-0">   
            <button class= "btn btn-friend shadow">  <i class="fas fa-user-friends"></i> Friend </button>
          </div>
        </div>
      <% end %>
  </div>
<% end %>

<% unless @pending_requests.empty? %>
  <div class="card my-5 py-3 bg-light shadow">
      <h2 class="center pb-3 text-dark border-bottom">Sent Friend Requests</h2> 
      <% @pending_requests.each do |user|%><!-- Shows all users that has sent current user a friend request -->
        <div class="d-flex align-items-center mb-2 border-bottom py-2">
          <div class="col-auto p-0 pl-5 text-capitalize"> 
            <%= link_to user_path(user) do %>
              <%= user.full_name %>
            <% end %>
          </div>
          <div class="col-auto p-0 px-1">|</div>
          <div class="col-auto p-0">
            <button class= "btn btn-secondary shadow" disabled> 
              <i class="fas fa-chalkboard-teacher"></i> Friend Request pending... 
            </button>
          </div>
        </div>
        <br><br>
      <% end %>
  </div>
<% end %>

<% unless @friend_requests.empty? %>
  <div class="card my-5 py-3 bg-light shadow">
      <h2 class="center pb-3 text-dark border-bottom">Pending Friend Requests</h2> 
      <% @friend_requests.each do |user|%> <!-- Shows all users friend requests has been sent to -->
        <div class="d-flex align-items-center mb-2 border-bottom py-2">
          <div class="col-auto p-0 pl-5 text-capitalize"> 
            <%= link_to user_path(user) do %>
            <%= user.full_name %>
            <% end %>
          </div>
          <div class="col-auto p-0 px-1">|</div>
          <div class="col-auto p-0">
            <button class= "btn btn-pending shadow" data-toggle="modal" data-target="#decisionModal">
                <i class="fas fa-envelope"></i> Pending Friend Request... 
            </button>
          </div>
        </div>
          <%= render 'friendships/decisionModal', object: user %>
        <br><br>
      <% end %>
  </div>
<% end %>


<div class="card my-5 py-3 bg-light shadow">
    <h2 class="center pb-3 text-dark border-bottom">Other Users</h2> 
    <% @users.each do |user|%> <!-- Shows all users friend requests has been sent to -->
      <% if current_user.id != user.id%><!-- Doesn't show current user on list -->
        <% unless possible_friend?(user) %> <!-- If user is not a friend and no request has been sent to or recieved from this user -->
          <div class="d-flex align-items-center mb-2 border-bottom pb-2">
            <div class="col-auto p-0 pl-5 text-capitalize"> 
              <%= link_to user_path(user) do %>
                <%= user.full_name %>
              <% end %>
            </div>
            <div class="col-auto p-0 px-1">|</div>
            <div class="col-auto p-0">
              <%= link_to user_friendships_path(user), method: :post do %>
                <button class= "btn btn-user shadow"> <i class="fas fa-share-square"></i> Send Friend Request? </button>
              <% end %>
            </div>
           </div>
            <br><br>
        <%end%>
      <% end %>
    <% end %>
</div>
</div>

app/views/users/show.html.erb
<h1>
  <%= @user.full_name%>
  <br>
</h1>

<div class="row">
  <div class=" mx-auto">

    <div class="col-m6 mb-2"> <%= image_tag @user.image.url if @user.image? %> </div>
    <% if current_user.id == @user.id %>
      <div class="col-m6">
        <button class= "btn btn-violete text-white font-weight-bold" data-toggle="modal" data-target="#imageUploadModal">
          Upload Profile Picture
        </button>
        <%= render 'shared/imageUploadModal', object: @user%>
      </div>
    <%end%>

  </div>
</div>


<h2 class="center mt-5 font-weight-bold border-top pt-5 ">Posts</h2>
<% @user.posts.each do |p|%>
  <%= render 'posts/post_layout', object: p %>
<% end %>